### ISSUE TITLE
Overfloating due to usage FixedPointToInt

### ISSUE THREAD

**Issue by AndrewDarcinc** [sovetskysoyuz/Stat-File-Exporter-dev#1]
Int32 has limits on the maximum size of a number it can store, namely 2147483647, which will cause an overflow already when its GDP is equal to or greater than 2.2B.
`Stat Export: January 2, 1836: CHI: Ming China: -2048434545`

**Comment by sovetskysoyuz** [comment]
I didn't have a particular reason for converting to Int32 except for trying to marginally reduce the size of the output to see if that would help with the log buffering issues (it didn't). I can have the scripted effects leave the CFixedPoint values as-is. Can't actually test to confirm that would fix the overflow as I don't have any 1.7 saves with more than 2.1B in global GDP so even annex_all doesn't produce a test case.
